/* ============================================================================
   build-atlas.js — generates assets/atlas.js for the master knowledge graph
   ----------------------------------------------------------------------------
   Scans the 50 book pages (via assets/library.js + each page's Book.mount DATA)
   and emits window.ATLAS = { groups, books, relations }.

   Relations come from two sources, best first:
     1. docs/atlas-content.json  — curated by the librarian agents
        { "summaries": { "<slug>": {"en","fa"} },
          "relations": [ {"a","b","why":{"en","fa"}} ] }
     2. derived fallback — books in different groups sharing a primary intent
        in assets/recommend.js (GROUP_TAGS / OVERRIDES).

   Run:  node tools/build-atlas.js
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

/* ── library manifest ────────────────────────────────────────────────────── */
const libSrc = read('assets/library.js');
const LIB = JSON.parse(libSrc.slice(libSrc.indexOf('['), libSrc.lastIndexOf(']') + 1));

/* ── per-book DATA (core line + published year) ──────────────────────────── */
const books = LIB.map(e => {
  const page = read(path.join(e.folder, e.slug + '.html'));
  const data = JSON.parse(page.split('Book.mount(')[1].split(/\);\s*<\/script>/)[0]);
  return {
    slug: e.slug, folder: e.folder, groupNum: e.groupNum,
    book: e.book, group: e.group,
    published: data.meta.published,
    core: data.core.name,
    coreLine: data.core.principle
  };
});

/* ── groups (tonal ramp cycles the five data tones) ──────────────────────── */
const TONES = ['--c-teal', '--c-blue', '--c-violet', '--c-amber', '--c-red'];
const groups = [];
for (const b of books) {
  if (!groups.find(g => g.num === b.groupNum)) {
    groups.push({ num: b.groupNum, name: b.group, varc: TONES[(b.groupNum - 1) % TONES.length] });
  }
}
groups.sort((a, b) => a.num - b.num);

/* ── curated content, if the librarians have produced it ─────────────────── */
let curated = null;
try { curated = JSON.parse(read('docs/atlas-content.json')); } catch (e) { /* not yet */ }

if (curated && curated.summaries) {
  for (const b of books) {
    if (curated.summaries[b.slug]) b.summary = curated.summaries[b.slug];
  }
}

let relations = [];
if (curated && Array.isArray(curated.relations) && curated.relations.length) {
  const known = new Set(books.map(b => b.slug));
  relations = curated.relations.filter(r => known.has(r.a) && known.has(r.b));
} else {
  /* derived fallback: parse the wizard's tag tables */
  const rec = read('assets/recommend.js');
  const grab = name => {
    const m = rec.match(new RegExp('var ' + name + ' = (\\{[\\s\\S]*?\\n  \\});'));
    return m ? new Function('return ' + m[1])() : {};
  };
  const GT = grab('GROUP_TAGS'), OV = grab('OVERRIDES');
  const intentOf = b => {
    const o = OV[b.slug] || {};
    const g = GT[b.groupNum] || {};
    return (o.intents || g.intents || [])[0] || null;
  };
  const byIntent = {};
  for (const b of books) {
    const it = intentOf(b);
    if (!it) continue;
    (byIntent[it] = byIntent[it] || []).push(b);
  }
  const seen = new Set();
  for (const it of Object.keys(byIntent)) {
    const list = byIntent[it];
    for (const b of list) {
      let added = 0;
      for (const o of list) {
        if (added >= 2) break;
        if (o.slug === b.slug || o.groupNum === b.groupNum) continue;
        const key = [b.slug, o.slug].sort().join('~');
        if (seen.has(key)) continue;
        seen.add(key); added++;
        relations.push({ a: b.slug, b: o.slug });
      }
    }
  }
}

const out = '/* Generated by tools/build-atlas.js — do not edit by hand.\n' +
  '   Curated layer: docs/atlas-content.json (librarian agents). */\n' +
  'window.ATLAS = ' + JSON.stringify({ groups, books, relations }, null, 2) + ';\n';
fs.writeFileSync(path.join(ROOT, 'assets/atlas.js'), out, 'utf8');
console.log('Wrote assets/atlas.js —', books.length, 'books,', groups.length, 'groups,',
  relations.length, 'relations' + (curated ? ' (curated)' : ' (derived)'));
